name: "Image cache set-up"

description: "Configures the conan cache"

inputs:
  faasm-version:
    description: "Faasm version"
    required: true

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    # This action is used to only pull all the images in a Faasm deployment
    # once per GHA workflow. To do so, it is first called on its own, and
    # follows (potentially) the write path where images are pulled and
    # saved to a temporary directory (using docker save). Then, it is called
    # in the "read" path, where images are loaded from the temporary directory.
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3
        #       - name: "Log in to DockerHub"
        #         uses: docker/login-action@v3
        #         with:
        #           registry: faasm.azurecr.io
        #           username: ${{ secrets.ACR_SERVICE_PRINCIPAL_ID }}
        #           password: ${{ secrets.ACR_SERVICE_PRINCIPAL_PASSWORD }}
    - uses: actions/cache@v4
      id: docker-image-cache
      with:
        path: /tmp/faasm-docker-images
        key: docker-image-cache-${{ inputs.faasm-version }}

    # ----- Write Path -----
    - name: "Pull all docker images"
      if: steps.docker-image-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p /tmp/faasm-docker-images
        ls -lart /tmp/faasm-docker-images/
        ./bin/inv_wrapper.sh docker.pull -c redis -c minio -c upload -c worker -c cli
    # Save all docker images to files. Annoyingly, I have not found the way
    # to do this in a loop in GHA
    - name: "Redis"
      if: steps.docker-image-cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: faasm.azurecr.io/redis:${{ inputs.faasm-version }}
        outputs: type=docker,dest=/tmp/faasm-docker-images/redis_${{ inputs.faasm-version }}.tar
    - name: "MinIO"
      if: steps.docker-image-cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: faasm.azurecr.io/minio:${{ inputs.faasm-version }}
        outputs: type=docker,dest=/tmp/faasm-docker-images/minio_${{ inputs.faasm-version }}.tar
    - name: "Upload"
      if: steps.docker-image-cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: faasm.azurecr.io/upload:${{ inputs.faasm-version }}
        outputs: type=docker,dest=/tmp/faasm-docker-images/upload_${{ inputs.faasm-version }}.tar
    - name: "Worker"
      if: steps.docker-image-cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: faasm.azurecr.io/worker:${{ inputs.faasm-version }}
        outputs: type=docker,dest=/tmp/faasm-docker-images/worker_${{ inputs.faasm-version }}.tar
    - name: "Faasm CLI"
      if: steps.docker-image-cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: faasm.azurecr.io/cli:${{ inputs.faasm-version }}
        outputs: type=docker,dest=/tmp/faasm-docker-images/cli_${{ inputs.faasm-version }}.tar

    # ----- Read Path -----
    - name: "Load all images from the temporary directory"
      if: steps.docker-image-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        docker load --input /tmp/redis_${{ inputs.faasm-version }}.tar
        docker load --input /tmp/minio_${{ inputs.faasm-version }}.tar
        docker load --input /tmp/upload_${{ inputs.faasm-version }}.tar
        docker load --input /tmp/worker_${{ inputs.faasm-version }}.tar
        docker load --input /tmp/cli_${{ inputs.faasm-version }}.tar
